
buttonColours = ["red", "blue", "green", "yellow"];

var gamePattern = [];  //to store the random sequence that computer generates

var userClickedPattern = [];  //to store the random sequence of clicks that user presses


var started = false;
var level = 0;


$(document).keypress( function (){   //for triggering keypress event on the whole body when user presses a button
                                      //and also for starting the game.............(5)
    if(!started){

$("#level-title").text("level "+level);
nextSequence();
started = true;

    }
});


$(".btn").click(function(){            //Users clicks the button sequence generated by computer....(2)

    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);
    
    playSound(userChosenColour);
    animatePress(userChosenColour);
    checkAnswer(userClickedPattern.length-1);
    
    });


 function checkAnswer(currentLevel){            //for checking or comparing computers sequence of button clicks to that of the user..................(5)
                                                //and if the user doesn't click the same sequence or if he clicks a different button to turn the screen red and play warning music

        if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
         console.log("sucess");           
        if (userClickedPattern.length === gamePattern.length) {   
        setTimeout(function(){
            nextSequence();
        }, 1000);
    }  
     }else{

           console.log("wrong");

           playSound("wrong");

           $("body").addClass("game-over");
            setTimeout(function(){
                $("body").removeClass("game-over");
            }, 200);

            $("h1").text("Game Over, Press Any Key to Restart");
            startOver();
            
        }       
}


function nextSequence(){   //computers generates random sequence of button clicks to start the game .....(1)

userClickedPattern = [];

level++;

$("#level-title").text("level "+level);

    var randomNumber = (Math.floor(Math.random() * 4));

    var randomChosenColour = buttonColours[randomNumber];

    gamePattern.push(randomChosenColour);

    $("#" + randomChosenColour).fadeOut(150).fadeIn(150);
  
   playSound(randomChosenColour);
  
}

function playSound(name){        //for playing different sounds on button clicks..........(3) 

    var audio = new Audio("sounds/"+name+".mp3");
    audio.play();

}


function animatePress(currentColour) {         //for animating the button through (.pressed) class in css..............(4)

    $("#"+currentColour).addClass("pressed");
    
    setTimeout(function(){
        $("#"+currentColour).removeClass("pressed");},
        100);
    
}


function startOver(){ //to start over the game if user clicks the wrong button
    level = 0;       // resetting the level to 0
     gamePattern = []; //resetting computers pattern to zero
     started = false;  //restarting the game
     

}









